//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cumplenotas.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cumplenotas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha guardado un backup en.
        /// </summary>
        internal static string backup1 {
            get {
                return ResourceManager.GetString("backup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los backups son poco seguros ya que son simplemente un archivo de texto sin encriptar.
        ///Es más recomendable copiar el archivo cumples.🎉🎁 con otro nombre..
        /// </summary>
        internal static string backup2 {
            get {
                return ResourceManager.GetString("backup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado al guardar la copia de seguridad.
        /// </summary>
        internal static string backuper {
            get {
                return ResourceManager.GetString("backuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar backup.
        /// </summary>
        internal static string backupert {
            get {
                return ResourceManager.GetString("backupert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup creado correctamente.
        /// </summary>
        internal static string backupt {
            get {
                return ResourceManager.GetString("backupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar cumpleaños de.
        /// </summary>
        internal static string editof {
            get {
                return ResourceManager.GetString("editof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Error al cargar los cumplenotas! :(
        ///El archivo debe estar corrupto o abierto por otro programa. ¿Desea volver a intentarlo?.
        /// </summary>
        internal static string errloading {
            get {
                return ResourceManager.GetString("errloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar cumplenotas.
        /// </summary>
        internal static string errloadingt {
            get {
                return ResourceManager.GetString("errloadingt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a felicitarle.
        /// </summary>
        internal static string greeting {
            get {
                return ResourceManager.GetString("greeting", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string UC1 {
            get {
                return ResourceManager.GetString("UC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización descargada.
        /// </summary>
        internal static string UC10 {
            get {
                return ResourceManager.GetString("UC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando desde la versión.
        /// </summary>
        internal static string UC11 {
            get {
                return ResourceManager.GetString("UC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a la última versión disponible.
        /// </summary>
        internal static string UC12 {
            get {
                return ResourceManager.GetString("UC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar y salir.
        /// </summary>
        internal static string UC2 {
            get {
                return ResourceManager.GetString("UC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando actualizaciones....
        /// </summary>
        internal static string UC3 {
            get {
                return ResourceManager.GetString("UC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo comprobar si existen actualizaciones
        ///Compruebe que dispone de conexión a internet.
        /// </summary>
        internal static string UC4 {
            get {
                return ResourceManager.GetString("UC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha encontrado una nueva versión
        ///Haga clic en actualizar para descargarla atuomáticamente.
        /// </summary>
        internal static string UC5 {
            get {
                return ResourceManager.GetString("UC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya está utilizando la última versión
        ///No es necesario actualizar.
        /// </summary>
        internal static string UC6 {
            get {
                return ResourceManager.GetString("UC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando....
        /// </summary>
        internal static string UC7 {
            get {
                return ResourceManager.GetString("UC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El programa se ha descargado correctamente.
        ///                
        ///Borre la versión actual y extraiga el archivo comprimido descargado en:.
        /// </summary>
        internal static string UC8 {
            get {
                return ResourceManager.GetString("UC8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea abrir la carpeta?.
        /// </summary>
        internal static string UC9 {
            get {
                return ResourceManager.GetString("UC9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a felicitarla.
        /// </summary>
        internal static string greetinga {
            get {
                return ResourceManager.GetString("greetinga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hoy cumplen años.
        /// </summary>
        internal static string morebd {
            get {
                return ResourceManager.GetString("morebd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a personas!.
        /// </summary>
        internal static string morebd2 {
            get {
                return ResourceManager.GetString("morebd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy es el cumpleaños de.
        /// </summary>
        internal static string morebdi1 {
            get {
                return ResourceManager.GetString("morebdi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Son muchas personas para un regalo individual! Mejor haced una macro-fiesta..
        /// </summary>
        internal static string morebdi2 {
            get {
                return ResourceManager.GetString("morebdi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hoy cumple años una persona!.
        /// </summary>
        internal static string onebd {
            get {
                return ResourceManager.GetString("onebd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy es el cumpleaños de.
        /// </summary>
        internal static string onebdi1 {
            get {
                return ResourceManager.GetString("onebdi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , ¿tienes pensado ya su regalo? ¡Por supuesto no olvides.
        /// </summary>
        internal static string onebdi2 {
            get {
                return ResourceManager.GetString("onebdi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que quieres eliminar el cumpleaños de.
        /// </summary>
        internal static string remove1 {
            get {
                return ResourceManager.GetString("remove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ? ¡Esto lo borrará de la faz de la tierra para siempre!.
        /// </summary>
        internal static string remove2 {
            get {
                return ResourceManager.GetString("remove2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Eliminar cumpleaños?.
        /// </summary>
        internal static string removet {
            get {
                return ResourceManager.GetString("removet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede añadir este cumpleaños porque ya hay una persona con el mismo nombre.
        /// </summary>
        internal static string samename {
            get {
                return ResourceManager.GetString("samename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo añadir el cumpleaños.
        /// </summary>
        internal static string samenamet {
            get {
                return ResourceManager.GetString("samenamet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si la aplicación no se abre con Windows, deberá ejecutarse manualmente para que pueda recordar los cumpleaños mediante una notificación. ¿Está seguro de que desea desactivar la aplicación del inicio de Windows?.
        /// </summary>
        internal static string warnwin {
            get {
                return ResourceManager.GetString("warnwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso importante.
        /// </summary>
        internal static string warnwint {
            get {
                return ResourceManager.GetString("warnwint", resourceCulture);
            }
        }
    }
}
